import { defineConfig } from "oxlint";

export default defineConfig({
  ignorePatterns: [
    ".agent/**",
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".continue/**",
    ".cursor/**",
    ".gemini/**",
    ".opencode/**",
    ".pi/**",
    ".roo/**",
    ".windsurf/**",
    "node_modules/**",
    ".output/**",
    ".nuxt/**",
    ".nitro/**",
    "dist/**",
    "desktop/src-tauri/target/**",
    "desktop/native-media/libdspeak_media/build/**",
  ],
  rules: {
    "no-chained-type-assertions": "error",
    "no-conditional-empty-object-spread": "error",
    "no-known-value-widening": "error",
    "no-module-mocking": "error",
    "no-object-parameters": "error",
    "no-reflect-apply": "error",
    "no-reflect-get": "error",
    "no-runtime-typeof": "error",
    "no-shape-in-symbol-names": "error",
    "no-unknown-parameters": "error",
    "no-unknown-returns": "error",
    "no-unknown-type-aliases": "error",
    "no-unsafe-dictionary-type": "error",
    "no-widen-then-assert": "error",
    "require-safety-comment-for-type-assertion": "error",
  },
});
