import { computed, readonly } from "vue";
import type { HybridMediaSessionApiContext } from "./types/hybrid-media-session.ts";

export function createHybridMediaSessionApi({
  activeProviderState,
  areTransportsIceConnected,
  connect,
  connected,
  connectionPhase,
  disconnect,
  echoDetected,
  error,
  getInboundRtpStats,
  getOutboundRtpStats,
  getVoiceTransportTimeout,
  getWebRTCDiagnosticStats,
  getWebRTCStatsSnapshot,
  iceConnectedBoth,
  isProducing,
  joinReady,
  lastInRoom,
  lastReceivedConsumerParams,
  lastSentClientRtpCapabilities,
  lifecycle,
  localVideoFeeds,
  markRemoteFirstFrame,
  markRemoteFramePresented,
  mediaConnectionState,
  mediaCapabilities,
  mediaPathMetrics,
  microphoneDeviceState,
  participantSfuRoundTripTimes,
  peerConnectionMetrics,
  peerRoundTripTimes,
  playbackState,
  prepareAudioPlayback,
  producers,
  consumers: consumerState,
  protocolState,
  protocolUpdateRequired,
  remoteAudioFeeds,
  remoteProducersCount,
  remoteVideoFeeds,
  restartAudioProduction,
  sharedAudioAttenuation,
  sharedAudioDucking,
  sharedAudioStats,
  sfuRoundTripTime,
  sendParticipantVoiceState,
  setMediaCapabilities,
  setRemoteScreenReceiving,
  setRemoteSystemAudioReceiving,
  setSharedAudioAttenuation,
  setSharedAudioVolume,
  setSystemAudioBitrate,
  startAudioProduction,
  startSystemAudioProduction,
  startVideoProduction,
  stopAudioProduction,
  stopSystemAudioProduction,
  stopVideoProduction,
  topologyGraph,
  topologyState,
  transportReady,
  applyOutputDeviceToAll,
  applyVolumeForTrack,
  applyVolumeForUser,
  ensureAudioElements,
}: HybridMediaSessionApiContext) {
  return {
    connected: readonly(connected),
    joinReady,
    error: readonly(error),
    transportReady: readonly(transportReady),
    iceConnectedBoth: readonly(iceConnectedBoth),
    mediaConnectionState: readonly(mediaConnectionState),
    mediaCapabilities: readonly(mediaCapabilities),
    connectionPhase: readonly(connectionPhase),
    lifecycle: readonly(lifecycle),
    protocolState: readonly(protocolState),
    protocolUpdateRequired: readonly(protocolUpdateRequired),
    playbackState: readonly(playbackState),
    microphoneDeviceState: readonly(microphoneDeviceState),
    isProducing,
    producers: readonly(producers),
    consumers: readonly(consumerState),
    localVideoFeeds: readonly(localVideoFeeds),
    markRemoteFirstFrame,
    markRemoteFramePresented,
    remoteVideoFeeds: readonly(remoteVideoFeeds),
    remoteAudioFeeds: readonly(remoteAudioFeeds),
    sharedAudioStats: readonly(sharedAudioStats),
    echoDetected: readonly(echoDetected),
    sharedAudioAttenuation,
    sharedAudioDucking: readonly(sharedAudioDucking),
    peerRoundTripTimes: readonly(peerRoundTripTimes),
    peerConnectionMetrics: readonly(peerConnectionMetrics),
    mediaPathMetrics: readonly(mediaPathMetrics),
    sfuRoundTripTime: readonly(sfuRoundTripTime),
    participantSfuRoundTripTimes: readonly(participantSfuRoundTripTimes),
    remoteProducersCount,
    lastInRoom,
    topologyState: readonly(topologyState),
    topologyGraph: readonly(topologyGraph),
    activeProvider: readonly(activeProviderState),
    lastSentClientRtpCapabilities: computed(() =>
      lastSentClientRtpCapabilities(),
    ),
    lastReceivedConsumerParams: computed(() => lastReceivedConsumerParams()),
    connect,
    disconnect,
    prepareAudioPlayback,
    restartAudioProduction,
    startAudioProduction,
    stopAudioProduction,
    startVideoProduction,
    stopVideoProduction,
    startSystemAudioProduction,
    stopSystemAudioProduction,
    setRemoteScreenReceiving,
    setRemoteSystemAudioReceiving,
    setSharedAudioAttenuation,
    setSharedAudioVolume,
    setSystemAudioBitrate,
    sendParticipantVoiceState,
    setMediaCapabilities,
    applyOutputDeviceToAll,
    applyVolumeForUser,
    applyVolumeForTrack,
    ensureAudioElements,
    getWebRTCStatsSnapshot,
    getOutboundRtpStats,
    getInboundRtpStats,
    getWebRTCDiagnosticStats,
    areTransportsIceConnected,
    getVoiceTransportTimeout,
  };
}
